Repository jaehyeongjung/Wine-project, pull requests merged in 2025-02, with the labels that each got.

#5 chore: globlas.css-add
  styles/globals.css
Labels: chore

#7 chore: global.css-color-add
  styles/globals.css
Labels: chore

#11 feat: 공통 컴포넌트 버튼 제작
  pages/_app.tsx
  pages/components/common/Button.module.css
  pages/components/common/Button.tsx
  pages/index.tsx
  public/images/google.svg
  public/images/kakao.svg
  tsconfig.json
Labels: feat, chore

#15 feat: 모달창 기능 및 기본 css 구현 #12
  pages/components/common/Modal.tsx
  pages/components/layout/Test.tsx
  pages/index.tsx
  public/images/CloseIcon.svg
  styles/Home.module.css
  styles/Modal.module.css
Labels: feat

#14 refactor: size 변수 social 제거 및 선택사항_13
  pages/components/common/Button.module.css
  pages/components/common/Button.tsx
  pages/index.tsx
Labels: refactor

#17 feat: 기기 감지를 위한 useDevice 훅 구현 및 header, landingpage 구현#10
  components/layout/Header.module.css
  components/layout/Header.tsx
  hooks/useDevice.tsx
  pages/index.module.css
  pages/index.tsx
  public/favicon.ico
  public/images/landing_01.svg
  public/images/landing_02.svg
  public/images/landing_03.svg
  public/images/landing_04.svg
  styles/globals.css
Labels: feat

#18 feat: 공통 input 제작 #9
  pages/components/common/Input.module.css
  pages/components/common/Input.tsx
  pages/index.tsx
  public/icons/search.png
Labels: feat

#22 refactor: 공통컴포넌트 input border-radius 수정#21
  pages/components/common/Input.tsx
Labels: refactor

#24 feat: 모달창 삭제하기 / 와인등록 레이아웃 구현 #23
  pages/components/common/Modal.module.css
  pages/components/common/Modal.tsx
  pages/components/layout/Modal/DeleteModalLayout.module.css
  pages/components/layout/Modal/DeleteModalLayout.tsx
  pages/components/layout/Modal/RegisterModalLayout.module.css
  pages/components/layout/Modal/RegisterModalLayout.tsx
  pages/components/layout/Test.tsx
  pages/test.module.css
  pages/test.tsx
  public/images/ImageUpload.svg
  styles/Home.module.css
Labels: feat

#25 feat: myprofile page 기초 셋팅 css 및 더미 데이터 적용
  components/layout/Header.module.css
  components/layout/HeaderVersion2.tsx
  pages/components/common/Input.module.css
  pages/components/common/Input.tsx
  pages/index.tsx
  pages/myprofile/MyUploadSection/MyUploadSection.module.css
  pages/myprofile/MyUploadSection/MyUploadSection.tsx
  pages/myprofile/ProfileSection/ProfileSection.module.css
  pages/myprofile/ProfileSection/ProfileSection.tsx
  pages/myprofile/[id].module.css
  pages/myprofile/[id].tsx
Labels: feat, refactor

#27 feat: 모달창 삭제하기 / 와인등록 레이아웃 구현 #23
  pages/components/common/DropDown.module.css
  pages/components/common/DropDown.tsx
  pages/components/common/Input.module.css
  pages/components/common/Input.tsx
  pages/components/layout/Modal/RegisterModalLayout.module.css
  pages/components/layout/Modal/RegisterModalLayout.tsx
  pages/test.module.css
  public/images/WineTypeArrowIcon.svg
Labels: feat, refactor

#29 feat: signup, login 페이지 구현 #20
  components/common/Button.module.css
  components/common/Button.tsx
  components/common/Card.tsx
  components/common/DropDown.module.css
  components/common/DropDown.tsx
  components/common/Input.module.css
  components/common/Input.tsx
  components/common/Modal.module.css
  components/common/Modal.tsx
  components/layout/Header.module.css
  components/layout/Header.tsx
  components/layout/Modal/DeleteModalLayout.module.css
  components/layout/Modal/DeleteModalLayout.tsx
  components/layout/Modal/RegisterModalLayout.module.css
  components/layout/Modal/RegisterModalLayout.tsx
  pages/components/layout/Footer.tsx
  pages/components/layout/Header.tsx
  pages/components/layout/Layout.tsx
  pages/index.tsx
  pages/login.module.css
  pages/login.tsx
  pages/myprofile/ProfileSection/ProfileSection.tsx
  pages/signup.module.css
  pages/signup.tsx
  pages/test.tsx
  public/images/blacklogo.svg
  public/images/whitelogo.svg
  public/vercel.svg
Labels: feat, chore

#31 feat: slider 컴포넌트 구현
  components/common/SliderGrop.module.css
  components/common/SliderGrop.tsx
  components/layout/Review.tsx
  pages/test.module.css
  pages/test.tsx
  public/images/ReviewThumbnail.svg
Labels: feat

#32 chore: wines 페이지 css 규격 맞춤 외 별점 박스 컴포넌트 제작
  components/common/StarRating.tsx
  pages/wines.module.css
  pages/wines.tsx
  public/icons/priceBtn.svg
  public/icons/star.svg
  public/icons/starColor.svg
  public/images/testWine.svg
Labels: feat, chore

#39 feat: 리뷰등록 모달 레이아웃 구현 및 글로벌css 수정 #28
  components/common/ModalStarRating.tsx
  components/common/SliderGrop.module.css
  components/common/SliderGrop.tsx
  components/layout/Review.module.css
  components/layout/Review.tsx
  pages/test.module.css
  pages/test.tsx
  public/fonts/PretendardVariable.woff2
  styles/globals.css
Labels: feat, refactor

#40 feat: signup, signin API 연결 및 axios 인스턴스 설정
  package-lock.json
  package.json
  pages/index.module.css
  pages/index.tsx
  pages/login.tsx
  pages/signup.tsx
  public/images/landingMobile_01.svg
  public/images/landingMobile_02.svg
  public/images/landingMobile_03.svg
  public/images/landingMobile_04.svg
  public/images/landingTablet_01.svg
  utils/api/auth.tsx
Labels: feat

#42 feat: slider 컴포넌트와 레이아웃 구조 수정 및 바텀시트 구현 #41
  components/common/BottomSheet.module.css
  components/common/BottomSheet.tsx
  components/common/Modal.module.css
  components/common/Modal.tsx
  components/common/Slider.module.css
  components/common/Slider.tsx
  components/common/SliderGrop.tsx
  components/common/SliderGroup.tsx
  components/layout/Modal/RegisterModalLayout.module.css
  components/layout/Modal/RegisterModalLayout.tsx
  components/layout/Modal/Review.module.css
  components/layout/Modal/Review.tsx
  package-lock.json
  package.json
  pages/test.module.css
  pages/test.tsx
  pages/wines/WineReview.tsx
Labels: feat, refactor

#43 refactor: 마이페이지 css 작업외 usedevice 훅을 이용한 반응형 디자인
  pages/myprofile/MyUploadSection/MyUploadSection.module.css
  pages/myprofile/MyUploadSection/MyUploadSection.tsx
  pages/myprofile/ProfileSection/ProfileSection.module.css
  pages/myprofile/ProfileSection/ProfileSection.tsx
  pages/myprofile/[id].module.css
  pages/myprofile/[id].tsx
  public/icons/dropDown.svg
  styles/globals.css
Labels: refactor

#47 feat: '와인등록/수정' + '리뷰 등록/수정' + '삭제하기' api 기능 구현 작업 #45
  components/common/DropDown.tsx
  components/common/Input.tsx
  components/common/ModalStarRating.tsx
  components/common/Slider.tsx
  components/layout/Modal/DeleteModalLayout.tsx
  components/layout/Modal/RegisterModalLayout.tsx
  components/layout/Modal/Review.tsx
  pages/test.tsx
  utils/api/product.tsx
  utils/api/review.tsx
Labels: feat, refactor

#51 feat: 토큰저장 및 signup페이지 에러로직 개선
  components/layout/HeaderVersion2.tsx
  hooks/useDevice.tsx
  package-lock.json
  package.json
  pages/ callback/kakao.tsx
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/api/wineApi.tsx
  pages/index.module.css
  pages/login.tsx
  pages/signup.tsx
  utils/api/auth.tsx
Labels: feat

#56 feat: wine-list의 슬라이드 구현 & 필터 영역 구현 (반응형 모달까지)
  components/ PriceSilde/PriceSlide.module.css
  components/ PriceSilde/PriceSlide.tsx
  pages/wines.module.css
  pages/wines.tsx
  public/icons/close.png
  public/icons/filterDropDown.png
  public/icons/leftBtn.png
  public/icons/rightBtn.png
Labels: feat

#57 feat: 이미지 post api연동 작업 #53
  components/layout/Modal/DeleteModalLayout.tsx
  components/layout/Modal/RegisterModalLayout.tsx
  components/layout/Modal/Review.tsx
  next.config.js
  pages/api/image.tsx
  pages/api/product.tsx
  pages/api/review.tsx
  pages/test.tsx
Labels: feat

#61 feat: 회원가입, 로그인페이지 기능개선
  middleware.ts
  pages/api/auth/[...nextauth].ts
  pages/api/wineApi.tsx
  pages/login.tsx
  pages/signup.tsx
Labels: feat

#62 refactor: 피드백 내용 수정 (modal 구현 )
  pages/api/winesApi.tsx
  pages/wines.module.css
  pages/wines.tsx
Labels: refactor

#63 feat: 마이페이지 구현
  components/PriceSilde/PriceSlide.module.css
  components/PriceSilde/PriceSlide.tsx
  components/layout/Header/HeaderWithProfile.tsx
  components/layout/Modal/RegisterModalLayout.tsx
  next.config.js
  pages/api/wineApi.tsx
  pages/index.tsx
  pages/myprofile/ProfileSection/ProfileSection.module.css
  pages/myprofile/ProfileSection/ProfileSection.tsx
  pages/myprofile/[id].tsx
  pages/wines.tsx
Labels: feat

#64 feat: wine-list page api 구현
  pages/api/winesApi.tsx
  pages/myprofile/MyUploadSection/MyUploadSection.tsx
  pages/wines.module.css
  pages/wines.tsx
Labels: feat

#65 feat: 상세페이지 api 연결 작업 #48
  components/common/Button.module.css
  components/common/Button.tsx
  components/common/Input.module.css
  components/common/Input.tsx
  components/common/wines/WineDetailCard.tsx
  components/common/wines/WineRating.tsx
  components/common/wines/WineReview.tsx
  components/common/wines/detail.module.css
  components/common/wines/wineDetailCard.module.css
  components/common/wines/wineRating.module.css
  components/common/wines/wineReview.module.css
  package-lock.json
  package.json
  pages/api/wines/wineReviewApi.ts
  pages/wines/WineRating.tsx
  pages/wines/WineReview.tsx
  pages/wines/[id].tsx
  public/images/noReview.svg
Labels: feat, refactor

#70 feat: myprofile 페이지 리뷰 및 와인 데이터 api 구현 #69
  components/layout/Header/HeaderWithProfile.tsx
  components/layout/Modal/Review.tsx
  pages/api/product.tsx
  pages/api/review.tsx
  pages/myprofile/DataCard/ReviewCard.module.css
  pages/myprofile/DataCard/ReviewCard.tsx
  pages/myprofile/DataCard/WineCard.module.css
  pages/myprofile/DataCard/WineCard.tsx
  pages/myprofile/MyUploadSection/MyUploadSection.module.css
  pages/myprofile/MyUploadSection/MyUploadSection.tsx
  pages/myprofile/[id].module.css
  pages/myprofile/[id].tsx
  pages/test.tsx
Labels: feat, refactor

#71 feat:상세페이지 수정하기/삭제하기 api작업중
  components/common/wines/WineRating.tsx
  components/common/wines/WineReview.tsx
  components/common/wines/wineRating.module.css
  components/common/wines/wineReview.module.css
  components/layout/Modal/DeleteModalLayout.tsx
  components/layout/Modal/Review.tsx
  pages/test.tsx
Labels: feat

#72 feat: 카카오 소셜 로그인 구현
  components/layout/Header/HeaderWithProfile.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/callback/kakao.tsx
  pages/index.tsx
  pages/login.tsx
  pages/myprofile/ProfileSection/ProfileSection.tsx
  pages/myprofile/[id].tsx
Labels: feat

#74 fix: 와인 리뷰의 삭제하기 기능과 수정하기 기능을 수정했습니다.
  components/common/wines/WineReview.tsx
  components/layout/Modal/DeleteModalLayout.tsx
  components/layout/Modal/Review.tsx
  package-lock.json
  pages/api/review.tsx
Labels: fix, refactor

#75 feat: 마이페이지에서 상세페이지로 라우트 기능
  components/common/wines/WineReview.tsx
  components/common/wines/wineReview.module.css
  pages/myprofile/DataCard/ReviewCard.module.css
  pages/myprofile/DataCard/ReviewCard.tsx
  pages/myprofile/[id].tsx
Labels: feat

#76 Feature/profile 페이지 헤더 이미지 로직 수정 및 라우팅/드롭다운 관련 로직 수정
  pages/myprofile/DataCard/ReviewCard.tsx
  pages/myprofile/ProfileSection/ProfileSection.tsx
Labels: feat
